### ISSUE TITLE
tf2 tutorials outdated

### ISSUE THREAD

**Issue by tkruse** [ros/geometry2#21]
This relates to pretty much every C++ tutorial linked here:
http://www.ros.org/wiki/tf2/Tutorials
did not check the python tutorials.

Mostly the packages / include subfolder names are wrong, dating back to 2010 before tf2 was cleaned up i guess. E.g.:

http://www.ros.org/wiki/tf2/Tutorials/Migration/TransformListener

```
Depend on tf_ros package. 
#include "tf2_cpp/transform_listener.h"
tf2::Buffer buffer;
tf2::TransformListener tfl(buffer);
```

should read:
depend on tf2_ros...   not tf_ros
include subfolder should be tf2_ros, not tf2_cpp
Missing include of tf2_ros/buffer.h

**Comment by tfoote** [comment]
Things I've found that need to be updated.  turtlesim::Velocity deprecated/removed

several things moved into tf2_ros such as transform_listener.

**Comment by bricerebsamen** [comment]
I agree with tkruse. And #20. Given the state of the documentation and so on, it appears that tf2 is not mature yet, so I will wait before migrating.

**Comment by jonbinney** [comment]
The python tutorials are also very outdated. Just tried using them and wasn't able to get anything working. For example, they seem to assume that the TransformListener is in tf2, although it has moved to tf2_ros:

http://wiki.ros.org/tf2/Tutorials/Writing%20a%20tf2%20listener%20%28Python%29

**Comment by airballking** [comment]
Related question: I looked at the tf2-version of the time travel tutorial:

http://wiki.ros.org/tf2/Tutorials/tf2%20and%20time%20%28C%2B%2B%29

It uses a tf2_ros::TransformListener::waitForTransform(...). Looking at the code in the repo, I cannot find a waitForTransform function. In fact, I just cloned the entire repo and recursively grepped for waitForTransform --nothing. 

Is waitForTransform(...) a deprecated feature under tf2 or is this particular tutorial outdated or am I overlooking something in the code?

**Comment by vrabaud** [comment]
Even more critical, some files do not exist anymore (and I therefore could not fix the tutorial myself):
http://wiki.ros.org/tf2/Tutorials/Writing%20a%20tf2%20broadcaster%20%28C%2B%2B%29
refers to trunk_cturtle/stacks/ros_pkg_tutorials/turtle_tf2/src/turtle_tf2_broadcaster.cpp

**Comment by trainman419** [comment]
+1; I ran into missing files for tf2 as well.

**Comment by trainman419** [comment]
This has also been asked on ROS answers, and remains sadly unanswered: http://answers.ros.org/question/123336/where-is-tf2_echo-and-turtle_tf2/

**Comment by destogl** [comment]
Hello all,

yesterday I finally managed to lookup transforms with tf2. I also posted my way on the [answers.ros.org](http://answers.ros.org/question/187433/tf2-example/#187611).

Is this way how should be done in tf2? What I do not understand is why isn't there tf2_ros::TransformListener::lookupTransform() method? Should be really done directly with buffer?

I would like to put a bit effort and time to correct general tutorials on http://www.ros.org/wiki/tf2/Tutorials , but before would like to check if my way is correct.

Thanks!

**Comment by trainman419** [comment]
Confirmed; that's the correct way to use tf2.

Having the buffer separate from the transformListener is advantageous in some applications, where there may not be a listener, such as when reading transforms from bag files, or when using tf2 as a standalone transform library inside a larger application.

**Comment by destogl** [comment]
Ok, but wouldn't be reasonable, to preserve "compatibility" to tf, put also lookupTransform method into tr2_ros::TransformListener, which will than call underlying function from buffer?

**Comment by tfoote** [comment]
tf2 is a new clean API. The point of changing the namespace is to allow us to clean up the API. If you want to use the tf API it's still available for compatibility. (It uses tf2 under the hood)

**Comment by destogl** [comment]
Hi again... I just created, or better say migrated, turtle_tf tutorial to [turtle_tf2](https://github.com/destogl/geometry_tutorials/tree/tf2_tutorial/turtle_tf2) tutorial. As soon as the [issue](https://github.com/ros/geometry_tutorials/issues/4) is solved they will be geometry_tutorials package. Now would be great if somebody has time to start rewriting tutorial pages, since I am not sure if I manage in the next few weeks.

**Comment by davetcoleman** [comment]
+1 I just ran into these missing tutorials as well

**Comment by tfoote** [comment]
Thanks to the work of @Shokoofeh in geometry_tutorials most of the tf2 tutorials have been filled out. I've walked through the c++ tutorials at: http://wiki.ros.org/tf2/Tutorials I still have the python tutorials to verify.

**Comment by tfoote** [comment]
I walked through all the python tf2 tutorials yesterday. They can now be followed.

**Comment by davetcoleman** [comment]
Awesome, thanks!

**Comment by AmaurX** [comment]
@tfoote I think there are still some problems with the cpp tf2 tutorials. 
waitForTransform doesn't appear to exist, and some part of codes don't add up between tutorials... I've managed to make it work any way, I may go and change it in the tutorials
